name: country_list_pick_with_nation
description: Flutter plugin project to pick country code, will show code country, dial code, flag country, and name country.
version: 0.0.5
homepage: https://github.com/luluneverdie/country-list-pick

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^1.1.1


dev_dependencies:
  google_fonts: ^1.1.1
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - flags/
