List<Map> nationalitiesEnglish = [
  {"name": "Afghan", "dial_code": "+93", "code": "AF"},
  {"name": "Aland Islands", "dial_code": "+358", "code": "AX"},
  {"name": "Albanian", "dial_code": "+355", "code": "AL"},
  {"name": "Algerian", "dial_code": "+213", "code": "DZ"},
  {"name": "AmericanSamoa", "dial_code": "+1684", "code": "AS"},
  {"name": "Andorran", "dial_code": "+376", "code": "AD"},
  {"name": "Angolan", "dial_code": "+244", "code": "AO"},
  {"name": "Anguilla", "dial_code": "+1264", "code": "AI"},
  {"name": "Antarctica", "dial_code": "+672", "code": "AQ"},
  {"name": "Antigua and Barbuda", "dial_code": "+1268", "code": "AG"},
  {"name": "Argentinian", "dial_code": "+54", "code": "AR"},
  {"name": "Armenian", "dial_code": "+374", "code": "AM"},
  {"name": "Aruba", "dial_code": "+297", "code": "AW"},
  {"name": "Australian", "dial_code": "+61", "code": "AU"},
  {"name": "Austrian", "dial_code": "+43", "code": "AT"},
  {"name": "Azerbaijani", "dial_code": "+994", "code": "AZ"},
  {"name": "Bahamian", "dial_code": "+1242", "code": "BS"},
  {"name": "Bahraini", "dial_code": "+973", "code": "BH"},
  {"name": "Bangladeshi", "dial_code": "+880", "code": "BD"},
  {"name": "Barbadian", "dial_code": "+1246", "code": "BB"},
  {"name": "Belarusian or Belarusan", "dial_code": "+375", "code": "BY"},
  {"name": "Belgian", "dial_code": "+32", "code": "BE"},
  {"name": "Belizean", "dial_code": "+501", "code": "BZ"},
  {"name": "Beninese", "dial_code": "+229", "code": "BJ"},
  {"name": "Bermuda", "dial_code": "+1441", "code": "BM"},
  {"name": "Bhutanese", "dial_code": "+975", "code": "BT"},
  {
    "name": "Bolivian, Plurinational State of",
    "dial_code": "+591",
    "code": "BO"
  },
  {"name": "Bosnian", "dial_code": "+387", "code": "BA"},
  {"name": "Botswanan", "dial_code": "+267", "code": "BW"},
  {"name": "Brazilian", "dial_code": "+55", "code": "BR"},
  {"name": "British Indian Ocean Territory", "dial_code": "+246", "code": "IO"},
  {"name": "Bruneian", "dial_code": "+673", "code": "BN"},
  {"name": "Bulgarian", "dial_code": "+359", "code": "BG"},
  {"name": "Burkinese", "dial_code": "+226", "code": "BF"},
  {"name": "Burundian", "dial_code": "+257", "code": "BI"},
  {"name": "Cambodian", "dial_code": "+855", "code": "KH"},
  {"name": "Cameroonian", "dial_code": "+237", "code": "CM"},
  {"name": "Canadian", "dial_code": "+1", "code": "CA"},
  {"name": "Cape Verdean", "dial_code": "+238", "code": "CV"},
  {"name": "Cayman Islands", "dial_code": "+ 345", "code": "KY"},
  {"name": "Central African Republic", "dial_code": "+236", "code": "CF"},
  {"name": "Chadian", "dial_code": "+235", "code": "TD"},
  {"name": "Chilean", "dial_code": "+56", "code": "CL"},
  {"name": "Chinese", "dial_code": "+86", "code": "CN"},
  {"name": "Christmas Island", "dial_code": "+61", "code": "CX"},
  {"name": "Cocos (Keeling) Islands", "dial_code": "+61", "code": "CC"},
  {"name": "Colombian", "dial_code": "+57", "code": "CO"},
  {"name": "Comoros", "dial_code": "+269", "code": "KM"},
  {"name": "Congolese", "dial_code": "+242", "code": "CG"},
  {
    "name": "Congo, The Democratic Republic of the Congo",
    "dial_code": "+243",
    "code": "CD"
  },
  {"name": "Cook Islands", "dial_code": "+682", "code": "CK"},
  {"name": "Costa Rican", "dial_code": "+506", "code": "CR"},
  {"name": "Cote d'Ivoire", "dial_code": "+225", "code": "CI"},
  {"name": "Croat or Croatian", "dial_code": "+385", "code": "HR"},
  {"name": "Cuban", "dial_code": "+53", "code": "CU"},
  {"name": "Cypriot", "dial_code": "+357", "code": "CY"},
  {"name": "Czech", "dial_code": "+420", "code": "CZ"},
  {"name": "Danish", "dial_code": "+45", "code": "DK"},
  {"name": "Djiboutian", "dial_code": "+253", "code": "DJ"},
  {"name": "Dominican", "dial_code": "+1767", "code": "DM"},
  {"name": "Dominican", "dial_code": "+1849", "code": "DO"},
  {"name": "Ecuadorean", "dial_code": "+593", "code": "EC"},
  {"name": "Egyptian", "dial_code": "+20", "code": "EG"},
  {"name": "Salvadorean", "dial_code": "+503", "code": "SV"},
  {"name": "Equatorial Guinea", "dial_code": "+240", "code": "GQ"},
  {"name": "Eritrean", "dial_code": "+291", "code": "ER"},
  {"name": "Estonian", "dial_code": "+372", "code": "EE"},
  {"name": "Ethiopian", "dial_code": "+251", "code": "ET"},
  {"name": "Falkland Islands (Malvinas)", "dial_code": "+500", "code": "FK"},
  {"name": "Faroe Islands", "dial_code": "+298", "code": "FO"},
  {"name": "Fijian", "dial_code": "+679", "code": "FJ"},
  {"name": "Finnish", "dial_code": "+358", "code": "FI"},
  {"name": "French", "dial_code": "+33", "code": "FR"},
  {"name": "French Guiana", "dial_code": "+594", "code": "GF"},
  {"name": "French Polynesia", "dial_code": "+689", "code": "PF"},
  {"name": "Gabonese", "dial_code": "+241", "code": "GA"},
  {"name": "Gambian", "dial_code": "+220", "code": "GM"},
  {"name": "Georgian", "dial_code": "+995", "code": "GE"},
  {"name": "German", "dial_code": "+49", "code": "DE"},
  {"name": "Ghanaian", "dial_code": "+233", "code": "GH"},
  {"name": "Gibraltar", "dial_code": "+350", "code": "GI"},
  {"name": "Greek", "dial_code": "+30", "code": "GR"},
  {"name": "Greenland", "dial_code": "+299", "code": "GL"},
  {"name": "Grenadian", "dial_code": "+1473", "code": "GD"},
  {"name": "Guadeloupe", "dial_code": "+590", "code": "GP"},
  {"name": "Guam", "dial_code": "+1671", "code": "GU"},
  {"name": "Guatemalan", "dial_code": "+502", "code": "GT"},
  {"name": "Guernsey", "dial_code": "+44", "code": "GG"},
  {"name": "Guinean", "dial_code": "+224", "code": "GN"},
  {"name": "Guinea-Bissau", "dial_code": "+245", "code": "GW"},
  {"name": "Guyanese", "dial_code": "+595", "code": "GY"},
  {"name": "Haitian", "dial_code": "+509", "code": "HT"},
  {"name": "Holy See (Vatican City State)", "dial_code": "+379", "code": "VA"},
  {"name": "Honduran", "dial_code": "+504", "code": "HN"},
  {"name": "Hong Kong", "dial_code": "+852", "code": "HK"},
  {"name": "Hungarian", "dial_code": "+36", "code": "HU"},
  {"name": "Icelandic", "dial_code": "+354", "code": "IS"},
  {"name": "Indian", "dial_code": "+91", "code": "IN"},
  {"name": "Indonesian", "dial_code": "+62", "code": "ID"},
  {
    "name": "Iranian",
    "dial_code": "+98",
    "code": "IR"
  },
  {"name": "Iraqi", "dial_code": "+964", "code": "IQ"},
  {"name": "Irish", "dial_code": "+353", "code": "IE"},
  {"name": "Isle of Man", "dial_code": "+44", "code": "IM"},
  {"name": "Israel", "dial_code": "+972", "code": "IL"},
  {"name": "Italian", "dial_code": "+39", "code": "IT"},
  {"name": "Jamaican", "dial_code": "+1876", "code": "JM"},
  {"name": "Japanese", "dial_code": "+81", "code": "JP"},
  {"name": "Jersey", "dial_code": "+44", "code": "JE"},
  {"name": "Jordanian", "dial_code": "+962", "code": "JO"},
  {"name": "Kazakh", "dial_code": "+77", "code": "KZ"},
  {"name": "Kenyan", "dial_code": "+254", "code": "KE"},
  {"name": "Kiribati", "dial_code": "+686", "code": "KI"},
  {
    "name": "North Korean",
    "dial_code": "+850",
    "code": "KP"
  },
  {"name": "Korea, Republic of South Korea", "dial_code": "+82", "code": "KR"},
  {"name": "Kuwaiti", "dial_code": "+965", "code": "KW"},
  {"name": "Kyrgyzstan", "dial_code": "+996", "code": "KG"},
  {"name": "Laotian", "dial_code": "+856", "code": "LA"},
  {"name": "Latvian", "dial_code": "+371", "code": "LV"},
  {"name": "Lebanese", "dial_code": "+961", "code": "LB"},
  {"name": "Lesotho", "dial_code": "+266", "code": "LS"},
  {"name": "Liberian", "dial_code": "+231", "code": "LR"},
  {"name": "Libyan", "dial_code": "+218", "code": "LY"},
  {"name": "Liechtenstein", "dial_code": "+423", "code": "LI"},
  {"name": "Lithuanian", "dial_code": "+370", "code": "LT"},
  {"name": "Luxembourg", "dial_code": "+352", "code": "LU"},
  {"name": "Macao", "dial_code": "+853", "code": "MO"},
  {"name": "Macedonian", "dial_code": "+389", "code": "MK"},
  {"name": "Madagascan", "dial_code": "+261", "code": "MG"},
  {"name": "Malawian", "dial_code": "+265", "code": "MW"},
  {"name": "Malaysian", "dial_code": "+60", "code": "MY"},
  {"name": "Maldivian", "dial_code": "+960", "code": "MV"},
  {"name": "Malian", "dial_code": "+223", "code": "ML"},
  {"name": "Maltese", "dial_code": "+356", "code": "MT"},
  {"name": "Marshall Islands", "dial_code": "+692", "code": "MH"},
  {"name": "Martinique", "dial_code": "+596", "code": "MQ"},
  {"name": "Mauritanian", "dial_code": "+222", "code": "MR"},
  {"name": "Mauritian", "dial_code": "+230", "code": "MU"},
  {"name": "Mayotte", "dial_code": "+262", "code": "YT"},
  {"name": "Mexican", "dial_code": "+52", "code": "MX"},
  {
    "name": "Micronesia, Federated States of Micronesia",
    "dial_code": "+691",
    "code": "FM"
  },
  {"name": "Moldovan", "dial_code": "+373", "code": "MD"},
  {"name": "Monacan", "dial_code": "+377", "code": "MC"},
  {"name": "Mongolian", "dial_code": "+976", "code": "MN"},
  {"name": "Montenegrin", "dial_code": "+382", "code": "ME"},
  {"name": "Montserrat", "dial_code": "+1664", "code": "MS"},
  {"name": "Moroccan", "dial_code": "+212", "code": "MA"},
  {"name": "Mozambican", "dial_code": "+258", "code": "MZ"},
  {"name": "Myanmar", "dial_code": "+95", "code": "MM"},
  {"name": "Namibian", "dial_code": "+264", "code": "NA"},
  {"name": "Nauru", "dial_code": "+674", "code": "NR"},
  {"name": "Nepalese", "dial_code": "+977", "code": "NP"},
  {"name": "Dutch", "dial_code": "+31", "code": "NL"},
  {"name": "Dutch", "dial_code": "+599", "code": "AN"},
  {"name": "New Caledonia", "dial_code": "+687", "code": "NC"},
  {"name": "New Zealand", "dial_code": "+64", "code": "NZ"},
  {"name": "Nicaraguan", "dial_code": "+505", "code": "NI"},
  {"name": "Nigerien", "dial_code": "+227", "code": "NE"},
  {"name": "Nigerian", "dial_code": "+234", "code": "NG"},
  {"name": "Niue", "dial_code": "+683", "code": "NU"},
  {"name": "Norfolk Island", "dial_code": "+672", "code": "NF"},
  {"name": "Northern Mariana Islands", "dial_code": "+1670", "code": "MP"},
  {"name": "Norwegian", "dial_code": "+47", "code": "NO"},
  {"name": "Omani", "dial_code": "+968", "code": "OM"},
  {"name": "Pakistani", "dial_code": "+92", "code": "PK"},
  {"name": "Palau", "dial_code": "+680", "code": "PW"},
  {
    "name": "Palestinian Territory, Occupied",
    "dial_code": "+970",
    "code": "PS"
  },
  {"name": "Panamanian", "dial_code": "+507", "code": "PA"},
  {"name": "Guinean", "dial_code": "+675", "code": "PG"},
  {"name": "Paraguayan", "dial_code": "+595", "code": "PY"},
  {"name": "Peruvian", "dial_code": "+51", "code": "PE"},
  {"name": "Filipino", "dial_code": "+63", "code": "PH"},
  {"name": "Pitcairn", "dial_code": "+872", "code": "PN"},
  {"name": "Polish", "dial_code": "+48", "code": "PL"},
  {"name": "Portuguese", "dial_code": "+351", "code": "PT"},
  {"name": "Puerto Rico", "dial_code": "+1939", "code": "PR"},
  {"name": "Qatari", "dial_code": "+974", "code": "QA"},
  {"name": "Romanian", "dial_code": "+40", "code": "RO"},
  {"name": "Russian", "dial_code": "+7", "code": "RU"},
  {"name": "Rwandan", "dial_code": "+250", "code": "RW"},
  {"name": "Reunion", "dial_code": "+262", "code": "RE"},
  {"name": "Saint Barthelemy", "dial_code": "+590", "code": "BL"},
  {
    "name": "Saint Helena, Ascension and Tristan Da Cunha",
    "dial_code": "+290",
    "code": "SH"
  },
  {"name": "Saint Kitts and Nevis", "dial_code": "+1869", "code": "KN"},
  {"name": "Saint Lucia", "dial_code": "+1758", "code": "LC"},
  {"name": "Saint Martin", "dial_code": "+590", "code": "MF"},
  {"name": "Saint Pierre and Miquelon", "dial_code": "+508", "code": "PM"},
  {
    "name": "Saint Vincent and the Grenadines",
    "dial_code": "+1784",
    "code": "VC"
  },
  {"name": "Samoa", "dial_code": "+685", "code": "WS"},
  {"name": "San Marino", "dial_code": "+378", "code": "SM"},
  {"name": "Sao Tome and Principe", "dial_code": "+239", "code": "ST"},
  {"name": "Saudi Arabian", "dial_code": "+966", "code": "SA"},
  {"name": "Senegalese", "dial_code": "+221", "code": "SN"},
  {"name": "Serbian", "dial_code": "+381", "code": "RS"},
  {"name": "Seychellois", "dial_code": "+248", "code": "SC"},
  {"name": "Sierra Leonian", "dial_code": "+232", "code": "SL"},
  {"name": "Singaporean", "dial_code": "+65", "code": "SG"},
  {"name": "Slovak", "dial_code": "+421", "code": "SK"},
  {"name": "Slovenian", "dial_code": "+386", "code": "SI"},
  {"name": "Solomon Islands", "dial_code": "+677", "code": "SB"},
  {"name": "Somali", "dial_code": "+252", "code": "SO"},
  {"name": "South African", "dial_code": "+27", "code": "ZA"},
  {"name": "South Sudan", "dial_code": "+211", "code": "SS"},
  {
    "name": "South Georgia and the South Sandwich Islands",
    "dial_code": "+500",
    "code": "GS"
  },
  {"name": "Spanish", "dial_code": "+34", "code": "ES"},
  {"name": "Sri Lankan", "dial_code": "+94", "code": "LK"},
  {"name": "Sudanese", "dial_code": "+249", "code": "SD"},
  {"name": "Surinamese", "dial_code": "+597", "code": "SR"},
  {"name": "Svalbard and Jan Mayen", "dial_code": "+47", "code": "SJ"},
  {"name": "Swazi", "dial_code": "+268", "code": "SZ"},
  {"name": "Swedish", "dial_code": "+46", "code": "SE"},
  {"name": "Swiss", "dial_code": "+41", "code": "CH"},
  {"name": "Syrian", "dial_code": "+963", "code": "SY"},
  {"name": "Taiwanese", "dial_code": "+886", "code": "TW"},
  {"name": "Tajik", "dial_code": "+992", "code": "TJ"},
  {
    "name": "Tanzanian",
    "dial_code": "+255",
    "code": "TZ"
  },
  {"name": "Thai", "dial_code": "+66", "code": "TH"},
  {"name": "Timor-Leste", "dial_code": "+670", "code": "TL"},
  {"name": "Togolese", "dial_code": "+228", "code": "TG"},
  {"name": "Tokelau", "dial_code": "+690", "code": "TK"},
  {"name": "Tonga", "dial_code": "+676", "code": "TO"},
  {"name": "Trinidadian", "dial_code": "+1868", "code": "TT"},
  {"name": "Tunisian", "dial_code": "+216", "code": "TN"},
  {"name": "Turkish", "dial_code": "+90", "code": "TR"},
  {"name": "Turkmen", "dial_code": "+993", "code": "TM"},
  {"name": "Turks and Caicos Islands", "dial_code": "+1649", "code": "TC"},
  {"name": "Tuvaluan", "dial_code": "+688", "code": "TV"},
  {"name": "Ugandan", "dial_code": "+256", "code": "UG"},
  {"name": "Ukrainian", "dial_code": "+380", "code": "UA"},
  {"name": "Emirati", "dial_code": "+971", "code": "AE"},
  {"name": "British", "dial_code": "+44", "code": "GB"},
  {"name": "American", "dial_code": "+1", "code": "US"},
  {"name": "Uruguayan", "dial_code": "+598", "code": "UY"},
  {"name": "Uzbek", "dial_code": "+998", "code": "UZ"},
  {"name": "Vanuatuan", "dial_code": "+678", "code": "VU"},
  {
    "name": "Venezuelan",
    "dial_code": "+58",
    "code": "VE"
  },
  {"name": "Vietnamese", "dial_code": "+84", "code": "VN"},
  {"name": "Virgin Islands, British", "dial_code": "+1284", "code": "VG"},
  {"name": "Virgin Islands, U.S.", "dial_code": "+1340", "code": "VI"},
  {"name": "Wallis and Futuna", "dial_code": "+681", "code": "WF"},
  {"name": "Yemeni", "dial_code": "+967", "code": "YE"},
  {"name": "Zambian", "dial_code": "+260", "code": "ZM"},
  {"name": "Zimbabwean", "dial_code": "+263", "code": "ZW"}
];
